name: "Update a Drupal 8+ remote instance"
description: 'SSH to server and execute Drush update commands on the Drupal 8+ instance'
inputs:
  path:
    description: 'Absolute path on the server where the instance is located'
    required: true
  server_name:
    description: 'Name of the server SSH name'
    required: true
    default: 'server'
  drush:
    description: 'Path to drush executable'
    required: false
    default: './vendor/bin/drush'
  robo:
    description: 'Path to robo executable'
    required: false
    default: './vendor/bin/robo'
  enable_extra_modules:
    description: 'A space-separated list of modules to be enabled after the deployment is complete. Modules must be installed in Drupal'
    required: false
  enable_maintenance_mode:
    description: 'Toggles maintenance mode during the deployment. Default value "true" enables the maintenance mode.'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: "Update Drupal instance"
      shell: bash
      run: |
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_maintenance_mode }}" == "true" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} state-set system.maintenance_mode TRUE; fi'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.robo }} site:update --enable-maintenance-mode=0 --update-locale=0'
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_extra_modules }}" != "" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} pm:enable ${{ inputs.enable_extra_modules }}; fi'
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} cache:rebuild'
        ssh ${{ inputs.server_name }} 'if [ "${{ inputs.enable_maintenance_mode }}" == "true" ]; then cd ${{ inputs.path }} && ${{ inputs.drush }} state-set system.maintenance_mode FALSE; fi'
